#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # args.domain="domain.tld"
    # args.is_public=1
    # args.language="fr"
    # args.admin="john"
    # args.password="1Strong-Password"
    # args.name="My_Mobilizon"

    test_upgrade_from.523a717924c090284820e88fe3e7fcec9433a8d6.name = "4.0.2~ynh1"

