#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.domain="domain.tld"
    args.is_public=1
    args.language="fr"
    args.admin="john"
    args.admin_emeil="john@example.tld"

    test_upgrade_from.06134f48fe688f151242a08e0a33563441a70759.name = "5.1.5~ynh4"
    test_upgrade_from.a457bd82dbf976f772a21a1482e15e5831db99b3.name = "5.2.0~ynh1"

