#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl  --action="stop" --log_path=systemd

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

if [ $change_domain -eq 1 ]; then
    yunohost user update "$ynh_user" --mail "$ynh_user@$domain" --add-mailalias "$app@$domain"
fi

ynh_backup_if_checksum_is_different "$install_dir/config.exs"
ynh_replace --match="$old_domain" --replace="$new_domain" --file="$install_dir/config.exs"
ynh_store_file_checksum "$install_dir/config.exs"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl  --action="start" --log_path=systemd --wait_until="Access Mobilizon.Web.Endpoint at"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
