#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_email=$(ynh_user_get_info --username="$admin" --key="mail")
ynh_app_setting_set --key="admin_email" --value="$admin_email"

ynh_user_password=$(ynh_string_random --length=30)
ynh_app_setting_set --key="ynh_user_password" --value="$ynh_user_password"

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression "Configuring yunohost users..."

yunohost user create "$ynh_user" -F "Mobilizon Notifications" --domain "$domain" --password "$ynh_user_password" -q 0
yunohost user update "$ynh_user" --add-mailalias "$app@$domain" --add-mailforward "$admin_email"

#=================================================
# CREATE A POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Configuring the PostgreSQL database..."

# FIXME: Really superuser ??
ynh_psql_db_shell  <<< "ALTER USER $db_user WITH SUPERUSER;"
ynh_psql_db_shell  <<< "CREATE EXTENSION IF NOT EXISTS postgis;"
ynh_psql_db_shell  <<< "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
ynh_psql_db_shell  <<< "CREATE EXTENSION IF NOT EXISTS unaccent;"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/live"

#=================================================
# MAKE SETUP
#=================================================
ynh_script_progression "Making setup..."

pushd "$install_dir/live"
    ynh_exec_as_app MOBILIZON_CONFIG_PATH="$MOBILIZON_CONFIG_PATH" MIX_ENV=prod \
        ./bin/mobilizon_ctl instance gen --force \
        --output "$MOBILIZON_CONFIG_PATH" \
        --output-psql "$install_dir/setub_db.psql" \
        --domain "$domain" \
        --instance-name "Mobilizon" \
        --admin-email "$app@$domain" \
        --dbhost localhost \
        --dbname "$db_name" \
        --dbuser "$db_user" \
        --dbpass "$db_pwd" \
        --listen-port "$port"
    ynh_safe_rm "$install_dir/setup_db.psql"
popd

ynh_config_add --template="ldap.exs" --destination="$install_dir/ldap.exs"
ynh_config_add --template="mail.exs" --destination="$install_dir/mail.exs"
ynh_config_add --template="uploads.exs" --destination="$install_dir/uploads.exs"

cat "$install_dir/ldap.exs" "$install_dir/mail.exs" "$install_dir/uploads.exs" >> "$MOBILIZON_CONFIG_PATH"
ynh_store_file_checksum "$MOBILIZON_CONFIG_PATH"

ynh_safe_rm "$install_dir/ldap.exs"
ynh_safe_rm "$install_dir/mail.exs"
ynh_safe_rm "$install_dir/uploads.exs"

chmod 400 "$MOBILIZON_CONFIG_PATH"
chown "$app:$app" "$MOBILIZON_CONFIG_PATH"

ynh_exec_as_app MOBILIZON_CONFIG_PATH="$MOBILIZON_CONFIG_PATH" "$install_dir/live/bin/mobilizon_ctl" migrate

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="$app daemon for Mobilizon"

#=================================================
# SETUP APPLICATION
#=================================================
ynh_script_progression "Finalizing installation..."

ynh_systemctl --service="$app" --action="start" --log_path=systemd --wait_until="Access Mobilizon.Web.Endpoint at"

# We generate a dummy password ... this will actually *not* be used because the admin is supposed to connect via the ldap
ynh_exec_as_app MOBILIZON_CONFIG_PATH="$MOBILIZON_CONFIG_PATH" "$install_dir/live/bin/mobilizon_ctl" \
    users.new "$admin_email" --admin --password "$(ynh_string_random --length=30)"

ynh_systemctl --service="$app" --action="stop" --log_path=systemd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path=systemd --wait_until="Access Mobilizon.Web.Endpoint at"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
