#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_package_version
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
path_url=$(ynh_app_setting_get --app=$app --key=path)
admin=$(ynh_app_setting_get --app=$app --key=admin)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)
language=$(ynh_app_setting_get --app=$app --key=language)
db_name=$(ynh_app_setting_get --app=$app --key=db_name)
db_user=$db_name
db_pwd=$(ynh_app_setting_get --app=$app --key=db_pwd)
port=$(ynh_app_setting_get --app=$app --key=port)
secret=$(ynh_app_setting_get --app=$app --key=secret)
admin_email=$(ynh_app_setting_get --app=$app --key=admin_email)

#=================================================
# CHECK VERSION
#=================================================
ynh_script_progression --message="Checking version..."

upgrade_type=$(ynh_check_app_version_changed)

abort_if_up_to_date
# previous function is what defines 'version', more precisely the 'previous version'
previous_version="${version}"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..."

if ! ynh_permission_exists --permission="admin"; then
	# Create the required permissions
	ynh_permission_create --permission="admin" --url="/admin" --allowed=$admin
fi

ynh_secure_remove --file="$final_path/$app/priv/data/GeoLite2-City.mmdb"

ynh_secure_remove --file="/usr/share/GeoIP"

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================
ynh_script_progression --message="Backing up the app before upgrading (may take a while)..."

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# restore it if the upgrade fails
	ynh_restore_upgradebackup
	ynh_clean_check_starting
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..."

ynh_systemd_action --service_name=$app --action="stop" --log_path=systemd --line_match="Stopped"

#=================================================
# UPGRADE FROM PREVIOUS VERSION
#=================================================

if ynh_version_gt "1.0.0~ynh1" "${previous_version}" ; then
	ynh_script_progression --message="Upgrade configuration to 1.0.0..."

	ynh_user_password=$(ynh_string_random --length=30)
	ynh_app_setting_set --app=$app --key=ynh_user_password --value=$ynh_user_password

	yunohost user create ${app}_notifs --firstname "Mobilizon" --lastname "Notifications" --mail ${app}_notifs@$domain --password "$ynh_user_password" -q 0
	yunohost user update ${app}_notifs --add-mailalias $app@$domain --add-mailforward $admin_email

	# Manage previous .env file
	ynh_backup_if_checksum_is_different --file="$final_path/$app/.env"
	ynh_delete_file_checksum --file="$final_path/$app/.env"
	ynh_secure_remove --file="$final_path/$app/.env"

	# Configure Mobilizon
	config="$final_path/$app/config/prod.secret.exs"
	ynh_add_config --template="../conf/prod.secret.exs" --destination="$config"

	# Implement ldap and mail
	cat "../conf/ldap.exs" >> "$config"
	cat "../conf/mail.exs" >> "$config"
	
	ynh_replace_string --match_string="__YNH_USER__" --replace_string="${app}_notifs" --target_file="$config"
	ynh_replace_string --match_string="__YNH_USER_PASSWORD__" --replace_string="${ynh_user_password}" --target_file="$config"

	# Recalculate and store the checksum of the file for the next upgrade.
	ynh_store_file_checksum --file="$config"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..."
	
	# Create a temporary directory
	tmpdir="$(mktemp -d)"
	
	# Backup the config file in the temp dir
	cp -a "$final_path/$app/config/prod.secret.exs" "$tmpdir/prod.secret.exs"

	# Backup upload dir
	rsync -a "$final_path/$app/uploads" "$tmpdir/."
	
	# Remove the app directory securely
	ynh_secure_remove --file="$final_path/$app"

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$final_path/$app"
	
	# Restore the config file
	cp -a "$tmpdir/prod.secret.exs" "$final_path/$app/config/prod.secret.exs"

	# Restore upload dir
	rsync -a "$tmpdir/uploads" "$final_path/$app/."
	
	# Remove the tmp directory securely
	ynh_secure_remove --file="$tmpdir"
fi

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading nginx web server configuration..."

# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression --message="Upgrading dependencies..."

ynh_install_app_dependencies $pkg_dependencies

if ynh_version_gt "1.0.3~ynh1" "${previous_version}" ; then
	ynh_script_progression --message="Mobilizon v1.0.3: Remove previous NodeJS"
	ynh_remove_nodejs
fi

ynh_install_nodejs --nodejs_version=$NODEJS_VERSION

lsb_name="$(lsb_release --codename --short)"
ynh_install_extra_app_dependencies --repo="deb http://packages.erlang-solutions.com/debian $lsb_name contrib" --package="$extra_pkg_dependencies" --key='https://packages.erlang-solutions.com/debian/erlang_solutions.asc'

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression --message="Making sure dedicated system user exists..."

# Create a dedicated user (if not existing)
ynh_system_user_create --username=$app --home_dir=$final_path

#=================================================
# SPECIFIC UPGRADE
#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression --message="Modifying a config file..."

config="$final_path/$app/config/prod.secret.exs"
ynh_backup_if_checksum_is_different --file="$config"
chmod o-rwx $config

#=================================================
# MAKE SETUP
#=================================================

# Give permission to the final_path
chown -R "$app":"$app" "$final_path"

pushd $final_path/$app/js
	ynh_use_nodejs
	ynh_script_progression --message="Installing NodeJS dependencies (this is going to take a while...)"
	sudo -u $app env PATH=$PATH yarn install
	ynh_script_progression --message="Building NodeJS application (this is going to take a while...)"
	sudo -u $app env PATH=$PATH NODE_BUILD_MEMORY=1024 yarn run build
popd

ynh_script_progression --message="Building Elixir application (this is going to take a while...)"
pushd $final_path/$app
	sudo -u "$app" MIX_ENV=prod mix local.hex --force
	sudo -u "$app" MIX_ENV=prod mix local.rebar --force
	ynh_exec_warn_less sudo -u "$app" MIX_ENV=prod mix deps.get
	ynh_exec_warn_less sudo -u "$app" MIX_ENV=prod mix compile
	sudo -u "$app" MIX_ENV=prod mix ecto.migrate
popd

#=================================================
# RUN APP MIGRATIONS
#=================================================

if ynh_version_gt "1.0.3~ynh1" "${previous_version}" ; then
	ynh_script_progression --message="Mobilizon v1.0.3: Refresh remote profiles to save avatars locally"
	pushd $final_path/$app
		sudo -u "$app" MIX_ENV=prod mix mobilizon.actors.refresh --all
	popd
fi

#=================================================
# STORE THE CONFIG FILE CHECKSUM
#=================================================
ynh_script_progression --message="Storing the config file checksum..."

# Recalculate and store the checksum of the file for the next upgrade.
ynh_store_file_checksum --file="$config"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Upgrading systemd configuration..."

# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================
ynh_script_progression --message="Securing files and directories..."

# Set permissions on app files
chown -R "$app":"$app" "$final_path"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..."

yunohost service add $app --description "$app daemon for Mobilizon"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..."

ynh_systemd_action --service_name=$app --action="start" --log_path=systemd --line_match="Access Mobilizon.Web.Endpoint at"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading nginx web server..."

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed"
